apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fzt-frontend-tls
  namespace: fzt-frontend
spec:
  secretName: fzt-frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fzt-frontend.romaine.life
