apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fzt-frontend
  namespace: fzt-frontend
spec:
  hostnames:
    - fzt-frontend.romaine.life
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: fzt-frontend
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: fzt-frontend
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
