apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-shared
  namespace: fzt-frontend
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 23411986-613b-4ba4-9802-5c7b5443444c
