apiVersion: v1
kind: Service
metadata:
  name: fzt-frontend
  namespace: fzt-frontend
  labels:
    app: fzt-frontend
spec:
  type: ClusterIP
  selector:
    app: fzt-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
